[Indexing] Fix #43 & Copy DataFrame for view (#55)
* Put oid into IndexMetadata Constructor

* Fix lint

* Copy the dataframe instead of creating view

* Flake8

* Yapf

* Fix numpy python2 writable flag issue
ValueError: cannot set WRITEABLE flag to True of this array

* yapf

* add comments

* yapf

* Fix lint

* Revert extractor hack