FIX-#7536: setuptools / ray version conflict in pkg_resources._vendor  (#7537)
Newer versions of setuptools with older versions of ray may result in
the following error:
ModuleNotFoundError: Make sure all required packages are installed: No
module named 'pkg_resources._vendor'

Newer versions of setuptools have deprecated pkg_resources ( see:
https://setuptools.pypa.io/en/latest/pkg_resources.html ) which versions
of ray<2.09 still reference in ray.data.init. Ray has replaced imports
of this package in 2.10

To fix this we update the ray dependency to ray 2.10+

<!-- Please give a short brief about these changes. -->

- [x] first commit message and PR title follow format outlined
[here](https://modin.readthedocs.io/en/latest/development/contributing.html#commit-message-formatting)
> **_NOTE:_** If you edit the PR title to match this format, you need to
add another commit (even if it's empty) or amend your last commit for
the CI job that checks the PR title to pick up the new PR title.
- [ ] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] passes `black --check modin/ asv_bench/benchmarks
scripts/doc_checker.py`
- [x] signed commit with `git commit -s` <!-- you can amend your commit
with a signature via `git commit -amend -s` -->
- [x] Resolves #7536
- [ ] tests added and passing
- [x] module layout described at `docs/development/architecture.rst` is
up-to-date <!-- if you have added, renamed or removed files or
directories please update the documentation accordingly -->

---------

Co-authored-by: Jonathan Shi <149419494+sfc-gh-joshi@users.noreply.github.com>