FIX-#5473: TypeError(DataFrameGroupBy.take() missing 1 required positional argument: 'indices')
Signed-off-by: Anatoly Myachev <anatoly.myachev@intel.com>